POST http://localhost:3000/api/guest/register

###

GET Http://localhost:5000/api/user/1


###

GET Http://localhost:5000/api/carrera/

###

GET Http://localhost:5000/api/carrera/

###
GET https://backend-algiii.onrender.com/api/carrera/