swagger: "3.0"
info:
  title: Backend-Alg-III API
  description: API description in Markdown.
  version: 1.0.0

host: api.example.com
basePath: /v1
schemes:
  - https

paths:
  /users:
    get:
      summary: Returns a list of users.
      description: Optional extended description in Markdown.
      produces:
        - application/json
      responses:
        200:
          description: OK
  /users/{id}:
    get:
      summary: Returns a user.
      description: Optional extended description in Markdown.
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          required: true
          type: integer
          description: The user's ID.
      responses:
        200:
          description: OK
        404:
          description: Not Found